if(POLICY CMP0057)
  cmake_policy(SET CMP0057 NEW)
endif()

if(NOT DEFINED MANIFEST OR NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "model manifest is missing")
endif()

file(STRINGS "${MANIFEST}" lines)
set(count 0)
set(names "")
foreach(line IN LISTS lines)
  if(line MATCHES "^[ \t]*#" OR line STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" fields "${line}")
  list(LENGTH fields field_count)
  if(NOT field_count EQUAL 5)
    message(FATAL_ERROR "manifest row does not have five fields: ${line}")
  endif()
  list(GET fields 0 name)
  list(GET fields 1 size)
  list(GET fields 2 sha)
  list(GET fields 3 url)
  if(name IN_LIST names)
    message(FATAL_ERROR "duplicate model name: ${name}")
  endif()
  list(APPEND names "${name}")
  if(NOT size MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "invalid size for ${name}: ${size}")
  endif()
  string(LENGTH "${sha}" sha_len)
  if(NOT sha_len EQUAL 64 OR NOT sha MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "invalid SHA-256 for ${name}: ${sha}")
  endif()
  if(NOT url MATCHES "^https://huggingface[.]co/.+/resolve/[0-9a-f]+/.+$")
    message(FATAL_ERROR "URL is not a pinned Hugging Face revision: ${url}")
  endif()
  string(REGEX REPLACE "^.*/resolve/([0-9a-f]+)/.*$" "\\1" revision "${url}")
  string(LENGTH "${revision}" revision_len)
  if(NOT revision_len EQUAL 40)
    message(FATAL_ERROR "revision is not an immutable 40-char commit: ${url}")
  endif()
  math(EXPR count "${count} + 1")
endforeach()
if(NOT count EQUAL 4)
  message(FATAL_ERROR "expected four pinned reference models, found ${count}")
endif()
